### ISSUE TITLE
Getting SIGSEGV signal on launching fullscreen

### ISSUE THREAD

**Issue by LOSEARDES77** [System64fumo/sysmenu#1] opened 2024-02-05 19:41 UTC
I am getting this message almost every time when i launch it on full screen and i get it sometimes when launching on normal mode and then the app exits
![image](https://github.com/AmirDahan/sysmenu/assets/84414230/be40c860-ae21-4c1b-8054-4fc1d1a487d6)

**Comment by LOSEARDES77** [comment] 2024-02-05 19:44
i have investigated why and saw that this signal code appears when a program accesses memory sections that it has not been assigned to

**Comment by System64fumo** [comment] 2024-02-05 22:02
That's weird does it only happen when using the fullscreen launch argument?
Because i also use -f and it doesn't happen for me?
Perhaps it's an -O3 issue
Try removing -O3 from the Makefile?

**Comment by System64fumo** [comment] 2024-02-05 22:43
Just made some quick changes i think now it should work fine?

**Comment by LOSEARDES77** [comment] 2024-02-05 23:10
I have tried that and keeps happening.
i have discoveredd that it has to do with gtk4-layer-shell.
When i tryed the gtk4-layer-demo and enabled the exclusive option it crashes the same way
What is intresting about this is that when i start the demo and enable the exclusive feature right away and not touch any other option befor it dosn't crash

**Comment by LOSEARDES77** [comment] 2024-02-05 23:25
I think it has to do with my gtk4-layer-shell installation nvm the tests they have for the ninja build fail

**Comment by System64fumo** [comment] 2024-02-06 01:49
For once my code was not broken, Glad you were able to find out what the cause was.
Closing this as it's not an issue with sysmenu.

**Closed as completed by System64fumo** 2024-02-06 01:49 UTC
